#!/bin/bash

#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=NLP1_jobs
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=6:00:00
#SBATCH --mem=50000M
#SBATCH --output=./SLURM_output/NLP1_run_all_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
cd $HOME/NLP1
# Activate your environment
source activate nlp1
# Run your code
srun python -u main.py --model all --pt_embed glove